route:
  group_by: ['alertname']
  group_wait: 1m
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'web.hook'
receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: https://webhook.site/281667ac-5921-4d5a-bbcf-fc267535f27a
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
